# Generated by Django 4.0 on 2021-12-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21, verbose_name='Language')),
                ('icon', models.ImageField(upload_to='languages_icons', verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('image', models.ImageField(upload_to='posts_images', verbose_name='Image')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('profile_image', models.ImageField(null=True, upload_to='profile_images', verbose_name='Profile Image')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('liked_posts', models.ManyToManyField(related_name='users_who_likes', to='codebook.Post')),
                ('snipped_posts', models.ManyToManyField(related_name='users_who_snipped', to='codebook.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codebook.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='codebook.language'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codebook.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codebook.post')),
            ],
        ),
    ]
