# Generated by Django 4.0 on 2021-12-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebook', '0002_create_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
