# Generated by Django 4.0 on 2021-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebook', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
