# Generated by Django 4.0 on 2021-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebook', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged',
            field=models.BooleanField(default=False, verbose_name='User Is Logged ?'),
        ),
    ]
